"""empty message

Revision ID: 386f1f170af1
Revises: 0766f00b220a
Create Date: 2021-06-03 17:53:34.577380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386f1f170af1'
down_revision = '0766f00b220a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach', sa.Column('players', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach', 'players')
    # ### end Alembic commands ###
