"""empty message

Revision ID: 4cbad27bf7b7
Revises: 7d2292d9c312
Create Date: 2021-05-30 17:41:54.496565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cbad27bf7b7'
down_revision = '7d2292d9c312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'recruiter', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recruiter', type_='unique')
    op.drop_table('sport')
    # ### end Alembic commands ###
