"""empty message

Revision ID: 67d622438457
Revises: f263bffca801
Create Date: 2021-05-30 16:58:15.928379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d622438457'
down_revision = 'f263bffca801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach', sa.Column('coachId', sa.Integer(), nullable=True))
    op.add_column('coach', sa.Column('role', sa.Integer(), nullable=True))
    op.add_column('coach', sa.Column('players', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'coach', ['coachId'])
    op.create_unique_constraint(None, 'coach', ['email'])
    op.create_unique_constraint(None, 'coach', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coach', type_='unique')
    op.drop_constraint(None, 'coach', type_='unique')
    op.drop_constraint(None, 'coach', type_='unique')
    op.drop_column('coach', 'players')
    op.drop_column('coach', 'role')
    op.drop_column('coach', 'coachId')
    # ### end Alembic commands ###
