"""empty message

Revision ID: 89be32e94b6c
Revises: 3b3299aeae24
Create Date: 2021-05-30 17:19:38.480905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89be32e94b6c'
down_revision = '3b3299aeae24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available__videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('video_size', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'academics', ['id'])
    op.create_unique_constraint(None, 'role', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'academics', type_='unique')
    op.drop_table('available__videos')
    # ### end Alembic commands ###
