"""empty message

Revision ID: 9a114455f2b8
Revises: 386f1f170af1
Create Date: 2021-06-06 10:42:39.397440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a114455f2b8'
down_revision = '386f1f170af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_user_id_fkey', 'role', type_='foreignkey')
    op.create_foreign_key(None, 'role', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.create_foreign_key('role_user_id_fkey', 'role', 'role', ['user_id'], ['id'])
    # ### end Alembic commands ###
