"""empty message

Revision ID: f263bffca801
Revises: e5d88658da40
Create Date: 2021-05-30 16:57:13.126954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f263bffca801'
down_revision = 'e5d88658da40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach', sa.Column('coachId', sa.Integer(), nullable=True, foreign_key=True))
    op.add_column('coach', sa.Column('role', sa.Integer(), nullable=True))
    op.add_column('coach', sa.Column('players', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'coach', ['id'])
    op.create_unique_constraint(None, 'coach', ['email'])
    op.create_unique_constraint(None, 'coach', ['coachId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coach', type_='unique')
    op.drop_constraint(None, 'coach', type_='unique')
    op.drop_constraint(None, 'coach', type_='unique')
    op.drop_column('coach', 'players')
    op.drop_column('coach', 'role')
    op.drop_column('coach', 'coachId')
    # ### end Alembic commands ###
